# Generated by Django 3.2.4 on 2021-07-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='topic',
            field=models.CharField(max_length=500),
        ),
    ]
